void print_alphabet(void);
void jack_bauer(void);
void print_alphabet_x10(void);
void times_table();
void print_to_98(int);
int add(int n, int m);
void print_times_table(int);
int _putchar(char);
int _islower(int c);
int print_last_digit(int n);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
